name: Static analysis

on:
  pull_request:
  push:
    branches-ignore: [master]

jobs:
  psalm:
    name: PHP ${{ matrix.php }}, PSL ${{ matrix.psl }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1']
        psl: ['1.9', '2.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Get Composer cache directory path
        id: composer-cache-dir
        run: |
          echo "::set-output name=path::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-dir.outputs.path }}
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Psalm cache
        uses: actions/cache@v2
        with:
          path: .cache/psalm
          key: psalm-${{ github.sha }}
          restore-keys: psalm-

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction

      - name: Install PSL v1.9
        if: ${{ matrix.psl == '1.9' }}
        run: composer require azjezz/psl:^${{ matrix.psl }} php-standard-library/psalm-plugin:^1.1

      - name: Install PSL v2.0
        if: ${{ matrix.psl == '2.0' }}
        run: composer require azjezz/psl:^${{ matrix.psl }} php-standard-library/psalm-plugin:^2.0

      - name: Run Psalm
        run: vendor/bin/psalm --output-format=github --no-progress
